## Module: ufc_1 - autogenerated documentation placeholder

# Uniform function call syntax
## plus - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc plus(x, y: int): int =
  return x + y

## multi - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc multi(x, y: int): int =
  return x * y

let
  a = 2
  b = 3
  c = 4

echo a.plus(b) == plus(a, b)
echo c.multi(a) == multi(c, a)

echo a.plus(b).multi(c)
echo c.plus(b).multi(a)
