## Module: oop_1 - autogenerated documentation placeholder

# This file provides a basic example of Object-Oriented Programming (OOP) in Nim.
# It defines a `Dog` object type with a `name` field and an associated `bark` procedure.
# Example
type
  Dog = object
    name: string

## bark - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc bark(self: Dog) =
  echo ("Woof! My name is " & self.name & "!")

let dog = Dog(name: "Buddy")
dog.bark()