## Module: procedure_overloading - autogenerated documentation placeholder

# This file demonstrates procedure overloading in Nim, allowing multiple procedures with the same name but different parameter signatures.
# It also illustrates the use of default arguments in procedure definitions.
# Procedure overloading

# proc with default argument
## getUserCity - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc getUserCity(firstName: string, lastName: string = "Perez"): string =
  case firstName
  of "Sergio": return "Sergio lives in Cadiz"
  of "Alicia": return "Alicia lives in Madrid"
  else: return "Unknown"

## getUserCity - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc getUserCity(userID: int): string =
  case userID
  of 1: return "UserID 1 lives in Tokyo"
  of 2: return "UserID 2 lives in Russia"
  else: return "Unknown UserID"

let
  p1 = getUserCity("Sergio")
  p2 = getUserCity(1)
  p3 = getUserCity("Alicia")
  p4 = getUserCity(2)

echo p1
echo p2
echo p3
echo p4