## Module: read_file - autogenerated documentation placeholder

# This file demonstrates how to read and display the content of a file specified as a command-line argument in Nim.
# It includes error handling for cases where no filename is provided or the specified file does not exist.
# Read a file from command line
import os

if paramCount() == 0:
  echo "Usage: readfile <filename>"
  quit()

# The first command-line argument is at index 0.
let filename = paramStr(1)

# Ensure the file exists.
if not fileExists(filename):
  echo "Error: File not found: ", filename
  quit()

try:
  let fileContent = readFile(filename)
  echo "--- File contents ---"
  echo fileContent
  echo " --- End contents ---"
except:
  echo "Error: Could not read file: ", filename