## Module: test_downloader - autogenerated documentation placeholder

import unittest
import std/os
import ../src/downloader
import ../src/utils

suite "YouTube Downloader Tests":
  let testOutputDir = "test_downloads"

  setup:
    createDirIfNotExists(testOutputDir)

  teardown:
    # Clean up test directory
    if dirExists(testOutputDir):
      removeDir(testOutputDir)

  test "Create YouTubeDownloader instance":
    let downloader = newYouTubeDownloader(testOutputDir)
    check downloader != nil

  test "Sanitize filename":
    check sanitizeFilename("test:file*name?.mp4") == "test_file_name_.mp4"

  test "Format duration":
    check formatDuration(125) == "2:05"

    # This test is now correct for the 1-hour case
    check formatDuration(3600) == "1:00:00"

    # This test is also correct
    check formatDuration(3665) == "1:01:05"
