## Module: change_argument - autogenerated documentation placeholder

# To change the argument must be declare as var
## changeArgument - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc changeArgument(argument: var int) =
  echo "Initial argument value: ", argument
  argument += 5

var temp = 10
changeArgument(temp)
echo temp
changeArgument(temp)
echo temp

