## Module: keep_odds - autogenerated documentation placeholder

## keepOdds - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc keepOdds(a: seq[int]): seq[int] =
  # result = @[] Sequences automatically initialize as empty
  for number in a:
    if number mod 2 == 1:
      result.add(number)

let f = @[1, 6, 4, 43, 57, 34, 98]
echo keepOdds(f)
