## Module: find - autogenerated documentation placeholder

# Use 'find' to locate the first match and get its start/end indices
import std/re

let text = "Call me at 555-0198 or 555-0123"
let (first, last) = findBounds(text, re"\d{3}-\d{4}")
if first != -1:
  echo "Found at: ", first, "..", last
  echo "Matched text: ", text[first..last]
