## Module: match_object - autogenerated documentation placeholder

# Using match objects with std/nre
import std/nre

let text = "Call me at 555-0198 or 555-0123"
let m = find(text, re"\d{3}-\d{4}")
if m.isSome:
  let matchObj = m.get()
  echo "Found at: ", matchObj.matchBounds.a, "..", matchObj.matchBounds.b
  echo "Matched text: ", text[matchObj.matchBounds]

