## Module: youtube_downloader - autogenerated documentation placeholder

import std/[os, strutils, strformat]
import cligen
import src/downloader
import src/utils
import src/types

const DOWNLOAD_FOLDER = "~/Downloads"

## displayVideoInfo - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc displayVideoInfo(info: VideoInfo) =
  echo "📹 Video Information:"
  echo &"  Title: {info.title}"
  echo &"  Duration: {info.duration}"
  echo &"  Uploader: {info.uploader}"
  echo &"  Views: {info.views}"
  echo &"  Upload Date: {info.uploadDate}"
  if info.description.len > 0:
    echo "  Description: {info.description.truncate(100)}..."

# Helper procedure to prevent code duplication in interactiveMode
## promptForFormatAndQuality - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc promptForFormatAndQuality(): (DownloadFormat, string, OutputFormat) =
  ## Prompts the user to select format and quality, returning their choices.

  # Set defaults
  var format = fmtVideo
  var quality = "720p"
  var outputFormat = ofMp4

  echo ""
  echo "🎵 Select format:"
  echo "1. Video"
  echo "2. Audio"
  stdout.write "Choice (1-2): "
  let formatChoice = readLine(stdin).strip()

  if formatChoice == "2":
    format = fmtAudio
    echo ""
    echo "🎵 Select audio format:"
    echo "1. MP3"
    echo "2. M4A"
    stdout.write "Choice (1-2): "
    let audioChoice = readLine(stdin).strip()
    outputFormat = if audioChoice == "1": ofMp3 else: ofM4a

    echo ""
    echo "🎚️ Select audio quality:"
    echo "1. 128k"
    echo "2. 192k"
    echo "3. 256k"
    echo "4. 320k"
    echo "5. Best"
    stdout.write "Choice (1-5): "
    let qualityChoice = readLine(stdin).strip()
    case qualityChoice
    of "1": quality = "128k"
    of "2": quality = "192k"
    of "3": quality = "256k"
    of "4": quality = "320k" # FIXED typo (was "4.")
    of "5": quality = "best"
    else: quality = "192k"
  else:
    # This is the video path
    format = fmtVideo
    outputFormat = ofMp4
    echo ""
    echo "🎬 Select video quality:"
    echo "1. 480p"
    echo "2. 720p"
    echo "3. 1080p"
    echo "4. 4K (2160p)"
    echo "5. Best available"
    stdout.write "Choice (1-5): "
    let qualityChoice = readLine(stdin).strip()
    case qualityChoice
    of "1": quality = "480p"
    of "2": quality = "720p"
    of "3": quality = "1080p"
    of "4": quality = "2160p"
    of "5": quality = "best"
    else: quality = "720p"

  return (format, quality, outputFormat)

## interactiveMode - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc interactiveMode() =
  echo "🎯 Nim YouTube Downloader - Interactive Mode"
  echo "=".repeat(50)

  # Create the downloader *once* outside the loop for efficiency
  let downloader = newYouTubeDownloader()

  while true:
    echo ""
    echo "Enter YouTube URL (or 'quit' to exit):"
    stdout.write "URL: "
    let url = readLine(stdin).strip()

    if url == "quit" or url == "exit":
      break

    if url.len == 0:
      continue

    echo ""
    echo "📋 Select download type:"
    echo "1. 🎥 Single video/audio"
    echo "2. 📁 Entire playlist"
    echo "3. ℹ️  Get video info only"
    echo "4. 🔙 Enter new URL"
    stdout.write "Choice (1-4): "

    let choice = readLine(stdin).strip()

    case choice
    of "1":
      # ---
      # REFACTORED: Call the helper proc
      # ---
      let (format, quality, outputFormat) = promptForFormatAndQuality()
      discard downloader.downloadSingle(url, format, quality, outputFormat)

    of "2":
      # ---
      # FIXED: Now provides options instead of just using defaults
      # REFACTORED: Call the helper proc
      # ---
      echo ""
      echo "📁 Configuring playlist download..."
      let (format, quality, outputFormat) = promptForFormatAndQuality()
      discard downloader.downloadPlaylist(url, format, quality, outputFormat)

    of "3":
      echo ""
      echo "ℹ️ Fetching video information..."
      # No need to create a new downloader
      let info = downloader.getVideoInfo(url)
      displayVideoInfo(info)

    of "4":
      continue

    else:
      printWarning("Invalid choice, please try again")

# --- Wrapper procedures (unchanged) ---

# proc downloadSingleWrapper(url: string, outputDir: string = getHomeDir() / "Downloads",
## downloadSingleWrapper - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc downloadSingleWrapper(url: string, outputDir: string = "DOWNLOAD_FOLDER",
                           format: string = "video", quality: string = "720p",
                           outputFormat: string = "mp4") =
  let downloader = newYouTubeDownloader(outputDir)
  let dlFormat = if format == "audio": fmtAudio else: fmtVideo
  let outFormat =
    case outputFormat.toLowerAscii()
    of "mp3": ofMp3
    of "m4a": ofM4a
    of "webm": ofWebm
    else: ofMp4

  discard downloader.downloadSingle(url, dlFormat, quality, outFormat)

## downloadPlaylistWrapper - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc downloadPlaylistWrapper(playlistUrl: string, outputDir: string = "DOWNLOAD_FOLDER",
                             format: string = "video", quality: string = "720p",
                             outputFormat: string = "mp4") =
  let downloader = newYouTubeDownloader(outputDir)
  let dlFormat = if format == "audio": fmtAudio else: fmtVideo
  let outFormat =
    case outputFormat.toLowerAscii()
    of "mp3": ofMp3
    of "m4a": ofM4a
    of "webm": ofWebm
    else: ofMp4

  discard downloader.downloadPlaylist(playlistUrl, dlFormat, quality, outFormat)

## bulkDownloadWrapper - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc bulkDownloadWrapper(filename: string, outputDir: string = "DOWNLOAD_FOLDER",
                         format: string = "video", quality: string = "720p",
                         outputFormat: string = "mp4") =
  let downloader = newYouTubeDownloader(outputDir)
  let dlFormat = if format == "audio": fmtAudio else: fmtVideo
  let outFormat =
    case outputFormat.toLowerAscii()
    of "mp3": ofMp3
    of "m4a": ofM4a
    of "webm": ofWebm
    else: ofMp4

  downloader.bulkDownload(filename, dlFormat, quality, outFormat)

## infoWrapper - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc infoWrapper(url: string) =
  let downloader = newYouTubeDownloader()
  let info = downloader.getVideoInfo(url)
  displayVideoInfo(info)

# --- Main execution block ---

when isMainModule:
  if paramCount() == 0:
    interactiveMode()
  else:
    dispatchMulti(
      [downloadSingleWrapper, help = {
        "url": "YouTube video URL",
        "outputDir": "Output directory for downloads",
        "format": "Download format (video/audio)",
        # ---
          # FIXED: Updated help text to be more inclusive
          # ---
        "quality": "Quality (e.g., 720p for video, 192k for audio, best)",
        "outputFormat": "Output format (mp4, mp3, m4a, webm)"
      }],
      [downloadPlaylistWrapper, help = {
        "playlistUrl": "YouTube playlist URL",
        "outputDir": "Output directory for downloads",
        "format": "Download format (video/audio)",
        "quality": "Quality (e.g., 720p for video, 192k for audio, best)",
        "outputFormat": "Output format (mp4, mp3, m4a, webm)"
      }],
      [bulkDownloadWrapper, help = {
        "filename": "File containing URLs (one per line)",
        "outputDir": "Output directory for downloads",
        "format": "Download format (video/audio)",
        "quality": "Quality (e.g., 720p for video, 192k for audio, best)",
        "outputFormat": "Output format (mp4, mp3, m4a, webm)"
      }],
      [infoWrapper, help = {
        "url": "YouTube video URL to get information"
      }]
    )
