## Module: downloader - autogenerated documentation placeholder

import std/[osproc, os, strutils, strformat, json, times]
import ./types
import ./utils

const DOWNLOAD_FOLDER = "~/Downloads"
type
  YouTubeDownloaderImpl* = ref object
    outputDir: string
    useYtdlp: bool

## newYouTubeDownloader - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc newYouTubeDownloader*(outputDir: string = DOWNLOAD_FOLDER): YouTubeDownloaderImpl =
  new(result)
  result.outputDir = outputDir

  # ---
  # CHANGED: Switched to cross-platform `findExe` and fixed logic
  # ---
  if findExe("yt-dlp").len > 0:
    result.useYtdlp = true
  elif findExe("youtube-dl").len > 0:
    result.useYtdlp = false
  else:
    # Neither was found
    printError("Neither yt-dlp nor youtube-dl found in your PATH.")
    printInfo("Please install one of them, preferably yt-dlp:")
    printInfo("  pip install yt-dlp")
    quit(1)

# ---
# NEW: Private helper proc to build format/quality args
# ---
## buildFormatArgs - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc buildFormatArgs(format: DownloadFormat, quality: string,
    outputFormat: OutputFormat): string =
  ## This proc contains the logic that was duplicated
  case format
  of fmtVideo:
    result.add " -f "
    case quality
    of "144p": result.add "\"best[height<=144]\""
    of "240p": result.add "\"best[height<=240]\""
    of "360p": result.add "\"best[height<=360]\""
    of "480p": result.add "\"best[height<=480]\""
    of "720p": result.add "\"best[height<=720]\""
    of "1080p": result.add "\"best[height<=1080]\""
    of "1440p": result.add "\"best[height<=1440]\""
    of "2160p": result.add "\"best[height<=2160]\""
    of "best": result.add "\"best\""
    else: result.add "\"best[height<=720]\"" # Default to 720p

  of fmtAudio:
    result.add " -x --audio-format " & $outputFormat
    case quality
    of "128k": result.add " --audio-quality 128K"
    of "192k": result.add " --audio-quality 192K"
    of "256k": result.add " --audio-quality 256K"
    of "320k": result.add " --audio-quality 320K"
    of "best": result.add " --audio-quality 0"
    else: result.add " --audio-quality 192K" # Default to 192k

## buildDownloadCommand - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc buildDownloadCommand*(self: YouTubeDownloaderImpl, url: string,
                           format: DownloadFormat, quality: string,
                           outputFormat: OutputFormat): string =
  var cmd = if self.useYtdlp: "yt-dlp" else: "youtube-dl"

    # Output template
  let outputTemplate = &"{self.outputDir}/%(title)s.%(ext)s"
  cmd.add &" -o \"{outputTemplate}\""
  cmd.add buildFormatArgs(format, quality, outputFormat)

  # Additional options
  cmd.add " --no-warnings"
  cmd.add " --restrict-filenames"
  cmd.add " " & quoteShell(url)

  return cmd

## buildPlaylistCommand - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc buildPlaylistCommand*(self: YouTubeDownloaderImpl, playlistUrl: string,
                           format: DownloadFormat, quality: string,
                           outputFormat: OutputFormat): string =
  var cmd = if self.useYtdlp: "yt-dlp" else: "youtube-dl"

  # Output template for playlists
  let outputTemplate = &"{self.outputDir}/%(playlist_title)s/%(title)s.%(ext)s"
  cmd.add &" -o \"{outputTemplate}\""
  cmd.add buildFormatArgs(format, quality, outputFormat)

  # Playlist options
  cmd.add " --yes-playlist"
  cmd.add " --no-warnings"
  cmd.add " --restrict-filenames"
  cmd.add " " & quoteShell(playlistUrl)

  return cmd

## downloadSingle - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc downloadSingle*(self: YouTubeDownloaderImpl, url: string,
                     format: DownloadFormat = fmtVideo,
                     quality: string = "720p",
                     outputFormat: OutputFormat = ofMp4): DownloadResult =
  createDirIfNotExists(self.outputDir)

  let cmd = self.buildDownloadCommand(url, format, quality, outputFormat)
  printInfo(&"Downloading: {url}")
  printInfo(&"Command: {cmd}")

  let startTime = cpuTime()
  let (output, exitCode) = execCmdEx(cmd)
  let duration = cpuTime() - startTime

  if exitCode == 0:
    printSuccess("Download completed successfully!")
    return DownloadResult(success: true, duration: duration)
  else:
    printError(&"Download failed with exit code: {exitCode}")
    printError(&"Error: {output}")
    return DownloadResult(success: false, error: output, duration: duration)

## downloadPlaylist - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc downloadPlaylist*(self: YouTubeDownloaderImpl, playlistUrl: string,
                       format: DownloadFormat = fmtVideo,
                       quality: string = "720p",
                       outputFormat: OutputFormat = ofMp4): DownloadResult =
  createDirIfNotExists(self.outputDir)

  let cmd = self.buildPlaylistCommand(playlistUrl, format, quality, outputFormat)
  printInfo(&"Downloading playlist: {playlistUrl}")

  let startTime = cpuTime()
  let (output, exitCode) = execCmdEx(cmd)
  let duration = cpuTime() - startTime

  if exitCode == 0:
    printSuccess("Playlist download completed successfully!")
    return DownloadResult(success: true, duration: duration)
  else:
    printError(&"Playlist download failed with exit code: {exitCode}")
    return DownloadResult(success: false, error: output, duration: duration)

## getVideoInfo - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc getVideoInfo*(self: YouTubeDownloaderImpl, url: string): VideoInfo =
  var cmd = if self.useYtdlp: "yt-dlp" else: "youtube-dl"
  cmd.add &" --dump-json --no-warnings {quoteShell(url)}"

  let (output, exitCode) = execCmdEx(cmd)

  if exitCode == 0 and output.len > 0:
    try:
      let jsonData = parseJson(output)
      return VideoInfo(
        title: jsonData{"title"}.getStr("Unknown"),
        duration: formatDuration(jsonData{"duration"}.getInt(0)),
        uploader: jsonData{"uploader"}.getStr("Unknown"),
        views: $jsonData{"view_count"}.getInt(0),
        uploadDate: jsonData{"upload_date"}.getStr("Unknown"),
        description: jsonData{"description"}.getStr("")
      )
    except JsonParsingError:
      printError("Failed to parse video information")
  else:
    printError("Failed to retrieve video information")

  return VideoInfo()

## bulkDownload - description placeholder
## Params: (add parameters description)
## Returns: (add return description)
proc bulkDownload*(self: YouTubeDownloaderImpl, filename: string,
                   format: DownloadFormat = fmtVideo,
                   quality: string = "720p",
                   outputFormat: OutputFormat = ofMp4) =
  if not fileExists(filename):
    printError(&"File not found: {filename}")
    return

  let urls = readFile(filename).strip().splitLines()
  var successful = 0
  var failed = 0

  printInfo(&"Starting bulk download of {urls.len} URLs")

  for i, url in urls:
    if url.strip().len == 0:
      continue

    # CHANGED: i + 1 for 1-based progress
    printProgress(i + 1, urls.len, &"Processing {url}")

    # CHANGED: More reliable playlist check
    if "list=" in url:
      let result = self.downloadPlaylist(url, format, quality, outputFormat)
      if result.success:
        successful.inc
      else:
        failed.inc
    else:
      let result = self.downloadSingle(url, format, quality, outputFormat)
      if result.success:
        successful.inc
      else:
        failed.inc

  printSuccess(&"Bulk download completed: {successful} successful, {failed} failed")
