## Module: types - autogenerated documentation placeholder

type
  DownloadFormat* = enum
    fmtVideo, fmtAudio

  VideoQuality* = enum
    q144p = "144p", q240p = "240p", q360p = "360p",
    q480p = "480p", q720p = "720p", q1080p = "1080p",
    q1440p = "1440p", q2160p = "2160p", qBest = "best"

  AudioQuality* = enum
    aq128k = "128k", aq192k = "192k", aq256k = "256k",
    aq320k = "320k", aqBest = "best"

  OutputFormat* = enum
    ofMp4 = "mp4", ofMp3 = "mp3", ofM4a = "m4a", ofWebm = "webm"

  DownloadResult* = object
    success*: bool
    filename*: string
    error*: string
    duration*: float

  VideoInfo* = object
    title*: string
    duration*: string
    uploader*: string
    views*: string
    uploadDate*: string
    description*: string

  YouTubeDownloader* = ref object
    outputDir*: string
    maxConcurrent*: int
