## Module: fith - autogenerated documentation placeholder

import ncurses

# --- Initialization ---
let stdscr = initscr()
discard cbreak() # Line buffering disabled, read chars one-by-one
discard noecho() # Don't echo input characters
discard start_color() # Enable color functionality

# --- Color Setup ---
# Define a color pair: ID 1, foreground CYAN, background BLACK
discard init_pair(1, COLOR_CYAN, COLOR_BLACK)

# --- Window Creation & Sizing ---
# Get screen dimensions to center the window
var maxY, maxX: cint
getmaxyx(stdscr, maxY, maxX)

# Define window geometry. Using cint is correct for ncurses.
let height: cint = 10
let width: cint = 40
let startY: cint = (maxY - height) div 2
let startX: cint = (maxX - width) div 2

# Create a new window. `newwin` returns a WINDOW object.
var win = newwin(height, width, startY, startX)

# --- Drawing ---
# A single refresh() is enough to clear the screen initially
discard refresh()

# Draw a box around the new window using default line characters
discard box(win, 0, 0)

# Set the window's color attribute
discard wattron(win, cint(COLOR_PAIR(1)))

# Print text *inside* the window.
# NOTE: (y, x) coordinates are relative to the window's top-left corner.
# FIX: Cast cint variables to `int` for the %d format specifier.
discard mvwprintw(win, 1, 1, "This is inside the new window!")
discard mvwprintw(win, 3, 1, "Window dimensions: %dx%d", int(height), int(width))
discard mvwprintw(win, 4, 1, "Window start: (y=%d, x=%d)", int(startY), int(startX))

# Turn the color attribute off
discard wattroff(win, cint(COLOR_PAIR(1)))

discard mvwprintw(win, 7, 2, "Press any key to exit.")

# CRITICAL: Refresh the *window* to make its content visible
discard wrefresh(win)

# --- Cleanup ---
discard getch() # Wait for user input

discard delwin(win) # Free the window's memory
discard endwin() # Restore terminal to its original state
