## Module: fourth - autogenerated documentation placeholder

import ncurses

let stdscr = initscr() # <-- CORRECT: Always capture stdscr
discard cbreak()
discard noecho()

# 1. Check for color support
if not has_colors():
  discard endwin()
  echo "Your terminal does not support color."
  quit(1)

# 2. Start color mode
discard start_color()

# 3. Define color pairs
# init_pair(pair_id, foreground_color, background_color)
# Pair 1: Red text on Black background
discard init_pair(1, COLOR_RED, COLOR_BLACK)
# Pair 2: Green text on White background
discard init_pair(2, COLOR_GREEN, COLOR_WHITE)

# Example 1: Bold text
discard attron(cint(A_BOLD)) # <-- FIX: Cast to cint
discard printw("This is BOLD text.\n")
discard attroff(cint(A_BOLD)) # <-- FIX: Cast to cint

# Example 2: Reversed text
discard attron(cint(A_REVERSE)) # <-- FIX: Cast to cint
discard mvprintw(3, 0, "This is REVERSED text.")
discard attroff(cint(A_REVERSE)) # <-- FIX: Cast to cint

# Example 3: Custom Color Pair 1
discard attron(cint(COLOR_PAIR(1))) # <-- FIX: Cast to cint
discard mvprintw(5, 0, "This is RED text on a BLACK background.")
discard attroff(cint(COLOR_PAIR(1))) # <-- FIX: Cast to cint

# Example 4: Combine Attributes (Bold + Color)
discard attron(cint(COLOR_PAIR(2) or A_BOLD)) # <-- FIX: Cast to cint
discard mvprintw(7, 0, "This is BOLD GREEN text on a WHITE background.")
discard attroff(cint(COLOR_PAIR(2) or A_BOLD)) # <-- FIX: Cast to cint

discard mvprintw(10, 0, "Press any key to exit...")
discard refresh()
discard getch()

discard endwin()

