## Module: third - autogenerated documentation placeholder

#[
printw(str): Prints a string at the current cursor position in the virtual
screen.

mvprintw(y, x, str): Moves the virtual cursor to (y, x) and then prints. You
will use this 99% of the time.

getch(): Reads a single key press from the user. If keypad is enabled, this
will return values like KEY_UP. If not, it will return the ASCII value of the
key (e.g., 'q'.ord).
]#
import ncurses

let stdscr = initscr() # <-- CORRECT: Capture stdscr
discard cbreak()
discard noecho()

var y, x: cint
getyx(stdscr, y, x) # <-- CORRECT: Pass stdscr
discard printw("Printed at default cursor (y=%d, x=%d)\n", y, x)

discard printw("This is printed on the next line.\n")

discard mvprintw(10, 20, "This was printed at (10, 20) with mvprintw.")

discard mvprintw(15, 0, "Press any key to exit...")
discard refresh()

discard getch() # Wait for key

discard endwin()
